kind: Deployment
apiVersion: apps/v1
metadata:
  name: gceme-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      env: canary
  template:
    metadata:
      name: backend
      labels:
        env: canary
    spec:
      containers:
      - name: backend
        env:
        - name: VERSION
          value: canary
