kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-app
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: sample-app
      labels:
        env: dev
    spec:
      containers:
      - name: sample-app
        image: sample-app
        imagePullPolicy: IfNotPresent
        env:
        - name: VERSION
          value: dev
