apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: frontend
requires:
  - path: ../base-image
  - path: ../test
  - path: ../backend
build:
  artifacts:
  - image: sample-app-frontend
    requires:
      - alias: BASE
        image: base
deploy:
  kustomize:
    paths:
    - k8s/dev
profiles:
- name: prod
  deploy:
    kustomize:
      paths:
      - k8s/prod
portForward:
  - resourceType: service
    resourceName: gceme-frontend
    namespace: default
    port: 80
    localPort: 8080
