substitutions:
  _REGION: us-central1
steps:
- name: 'gcr.io/k8s-skaffold/skaffold:v1.24.0'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    # Build but dont push images
    skaffold build --file-output=/workspace/artifacts.json \
                   --default-repo gcr.io/$PROJECT_ID \
                   --push=false

    # Test images
    skaffold test --build-artifacts=/workspace/artifacts.json

    # Push images
    skaffold build --file-output=/workspace/artifacts.json \
                   --default-repo gcr.io/$PROJECT_ID \
                   --push=true
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:debian_component_based'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud config set api_endpoint_overrides/clouddeploy "https://staging-clouddeploy.sandbox.googleapis.com/"
    gcloud alpha deploy apply --file deploy.yaml --region ${_REGION}
    gcloud alpha deploy releases create $SHORT_SHA-$(date +%s) \
                        --delivery-pipeline web-app \
                        --region ${_REGION} \
                        --build-artifacts /workspace/artifacts.json
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-gceme-artifacts/'
    paths:
    - '/workspace/artifacts.json'
options:
  machineType: N1_HIGHCPU_32
#  workerPool: 'projects/vic-e2e-cicd/locations/us-central1/workerPools/default'
timeout: 3600s