substitutions:
  _CLUSTER_NAME: default
  _REGION: us-west2
steps:
- name: 'gcr.io/k8s-skaffold/skaffold:v1.22.0'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    skaffold build --file-output=/workspace/artifacts.json --default-repo gcr.io/$PROJECT_ID
    cat artifacts.json
    skaffold test --build-artifacts=/workspace/artifacts.json
- name: 'gcr.io/k8s-skaffold/skaffold:v1.22.0'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    cd frontend
    skaffold render --profile prod \
                    --build-artifacts=/workspace/artifacts.json \
                    --default-repo gcr.io/$PROJECT_ID \
                    --output /workspace/prod.yaml
- name: 'gcr.io/k8s-skaffold/skaffold:v1.22.0'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud container clusters get-credentials $_CLUSTER_NAME --region $_REGION --project $PROJECT_ID
    cat /workspace/prod.yaml
    # TODO: Does not work, default repo is getting wiped
    # skaffold apply /workspace/prod.yaml
    kubectl apply -f /workspace/prod.yaml --wait --prune --all
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-gceme-artifacts/'
    paths:
    - '/workspace/artifacts.json'
    - '/workspace/prod.yaml'
options:
  machineType: N1_HIGHCPU_8
timeout: 3600s