apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: full-stack
requires:
  - path: validate/
build:
  local:
    concurrency: 0
  artifacts:
    - image: sample-app
      context: ./
deploy:
  kustomize:
    paths:
      - k8s/dev/
profiles:
  - name: staging
    deploy:
      kustomize:
        paths:
          - k8s/staging/
  - name: canary
    deploy:
      kustomize:
        paths:
        - k8s/canary/
  - name: prod
    deploy:
      kustomize:
        paths:
          - k8s/prod/
portForward:
  - resourceType: service
    resourceName: sample-app-dev
    port: 8080
