apiVersion: skaffold/v2beta13
kind: Config
test:
  # Unit tests, remotely vis Cloud Build
  - image: sample-app-backend-dev
    custom:
    - command: gcloud builds submit .
  # Image scan locally
  - image: sample-app-backend-dev
    custom:
    - command: ./hack/scan.sh $IMAGE
  - image: sample-app-frontend-dev
    custom:
    - command: ./hack/scan.sh $IMAGE
