apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: full-stack
requires:
  - path: frontend
  - path: backend
profiles:
  - name: prod
    deploy:
      kustomize:
        paths:
          - frontend/k8s/prod
          - backend/k8s/prod
        flags:
          apply:
            - "--prune=true"