apiVersion: skaffold/v2beta13
kind: Config
requires:
  - path: skaffold-test.yaml
build:
  artifacts:
  - image: sample-app-backend-dev
    context: cmd/backend
    # buildpacks:
    #   builder: "gcr.io/buildpacks/builder:v1"
  - image: sample-app-frontend-dev
    context: cmd/frontend
    # buildpacks:
    #   builder: "gcr.io/buildpacks/builder:v1"
  tagPolicy:
    sha256: {}
deploy:
  kustomize:
    paths:
    - k8s/dev/
