apiVersion: skaffold/v2beta13
kind: Config
requires:
  - path: skaffold-test.yaml
build:
  artifacts:
  - image: gcr.io/vicnastea/sample-app-backend-dev
    context: cmd/backend
  - image: gcr.io/vicnastea/sample-app-frontend-dev
    context: cmd/frontend
  tagPolicy:
    sha256: {}
deploy:
  kustomize:
    paths:
    - k8s/dev/
