apiVersion: skaffold/v2beta13
kind: Config
build:
  artifacts:
    - image: test-image
      context: .
      docker:
        dockerfile: hack/test-image/Dockerfile
test:
  # Unit tests, remotely vis Cloud Build
  - image: sample-app-backend-dev
    custom:
    - command: docker run $IMAGE go test
  - image: test-image
    custom:
    - command: docker run $IMAGE ./hack/validate.sh
  