apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: backend
requires:
  - path: ../base-image
  - path: ../validate
build:
  artifacts:
  - image: sample-app-backend
    requires:
    - alias: BASE
      image: base
test:
  - image: sample-app-backend
    custom:
    - command: docker run $IMAGE go test
deploy:
  kustomize:
    paths:
    - k8s/dev
profiles:
- name: prod
  deploy:
    kustomize:
      paths:
      - k8s/prod
portForward:
  - resourceName: gceme-backend
    resourceType: Service
    port: 8080
    localPort: 8081
