kind: Deployment
apiVersion: apps/v1
metadata:
  name: gceme-backend
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: backend
      labels:
        env: dev
    spec:
      containers:
      - name: backend
        image: sample-app-backend
        imagePullPolicy: IfNotPresent
        env:
        - name: VERSION
          value: dev
        - name: REDIS_URL
          value: redis:6379
