apiVersion: redis.cnrm.cloud.google.com/v1beta1
kind: RedisInstance
metadata:
  name: redis
spec:
  displayName: Redis Instance
  region: us-central1
  authorizedNetworkRef:
    name: default
  tier: BASIC
  memorySizeGb: 16
  connectMode: PRIVATE_SERVICE_ACCESS
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: default
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: true
