kind: Deployment
apiVersion: apps/v1
metadata:
  name: gceme-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      env: staging
  template:
    metadata:
      name: backend
      labels:
        env: staging
    spec:
      containers:
      - name: backend
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
        - name: VERSION
          value: staging
        - name: REDIS_URL
          value: 192.192.0.3:6379
