kind: Deployment
apiVersion: apps/v1
metadata:
  name: gceme-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: backend
      labels:
        env: production
    spec:
      containers:
      - name: backend
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: VERSION
          value: production
        - name: REDIS_URL
          value: 192.168.2.3:6379
