kind: Deployment
apiVersion: apps/v1
metadata:
  name: gceme-frontend
spec:
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    
    spec:
      containers:
      - name: frontend
        image: gcr.io/vic-cd-demo/sample-app-frontend-dev
        imagePullPolicy: IfNotPresent
        env:
        - name: VERSION
          value: dev
