kind: Deployment
apiVersion: apps/v1
metadata:
  name: gceme-frontend
spec:
  selector:
    matchLabels:
      app: gceme
      role: frontend
      env: base
  template:
    metadata:
      name: frontend
      labels:
        app: gceme
        role: frontend
        env: base
    spec:
      containers:
      - name: frontend
        image: sample-app-frontend
        command:
        - /go/src/frontend/frontend
        args:
        - -backend-service=http://gceme-backend:8080
        env:
        - name: VERSION
          value: base
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        imagePullPolicy: Always
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 1
          httpGet:
            path: /healthz
            port: 80
        ports:
        - name: frontend
          containerPort: 80
