kind: Deployment
apiVersion: apps/v1
metadata:
  name: gceme-backend
spec:
  selector:
    matchLabels:
      app: gceme
      role: backend
      env: base
  template:
    metadata:
      name: backend
      labels:
        app: gceme
        role: backend
        env: base
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      containers:
      - name: backend
        image: sample-app-backend
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: VERSION
          value: base
        imagePullPolicy: Always
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 1
          httpGet:
            path: /healthz
            port: 8080
        ports:
        - name: backend
          containerPort: 8080
