name: ci

# Run this workflow every time a new commit pushed to your repository
on:
 push:
   branches:
     - kustomize

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build-image:
    # Name the Job
    name: Build Images
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push frontend
        id: build_frontend
        uses: docker/build-push-action@v2
        with:
          context: cmd/frontend
          file: cmd/frontend/Dockerfile
          push: true
          tags: viglesiasce/sample-app-frontend:kustomize
      
      -
        name: Build and push backend
        id: build_backend
        uses: docker/build-push-action@v2
        with:
          context: cmd/backend
          file: cmd/backend/Dockerfile
          push: true
          tags: viglesiasce/sample-app-backend:kustomize