kind: Deployment
apiVersion: apps/v1
metadata:
  name: gceme-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      labels:
        env: production
    spec:
      containers:
      - name: frontend
        env:
        - name: VERSION
          value: production
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
