apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: 0e00c70e-1768-4e64-a242-b05116ae76f0
  name: gceme-frontend
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: gceme
    role: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: 0e00c70e-1768-4e64-a242-b05116ae76f0
  name: gceme-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gceme
      env: production
      role: frontend
  template:
    metadata:
      labels:
        app: gceme
        app.kubernetes.io/managed-by: skaffold
        env: production
        role: frontend
        skaffold.dev/run-id: 0e00c70e-1768-4e64-a242-b05116ae76f0
      name: frontend
    spec:
      containers:
      - env:
        - name: VERSION
          value: production
        image: us-central1-docker.pkg.dev/vic-e2e-cicd/web-app/sample-app-frontend:v0.0.1-alpha.1-70-gde47622-dirty@sha256:b7789087cf6eeb0ea863600e233b5e50589db25f73004123a3b9a41683916df9
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 8080
          name: frontend
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: 0e00c70e-1768-4e64-a242-b05116ae76f0
  name: gceme-backend
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gceme
    role: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold
    skaffold.dev/run-id: 0e00c70e-1768-4e64-a242-b05116ae76f0
  name: gceme-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gceme
      env: production
      role: backend
  template:
    metadata:
      labels:
        app: gceme
        app.kubernetes.io/managed-by: skaffold
        env: production
        role: backend
        skaffold.dev/run-id: 0e00c70e-1768-4e64-a242-b05116ae76f0
      name: backend
    spec:
      containers:
      - env:
        - name: VERSION
          value: production
        image: us-central1-docker.pkg.dev/vic-e2e-cicd/web-app/sample-app-backend:v0.0.1-alpha.1-70-gde47622-dirty@sha256:bf3c8c72ed6948b75424e8823d3ca0e62dc1e66270488bb93e8d51a760224b33
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 8080
          name: backend
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
